spring:
  application:
    name: tlias-cms

spring.datasource:
  url: jdbc:mysql://localhost:3306/tlias
  username: root
  password: password

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml