spring:
  application:
    name: tlias-cms

  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    username: your_username
    password: your_password
  servlet:
    multipart:
      # max single file size
      max-file-size: 10MB
      # max total size including all files and other request parameters
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG