spring:
  application:
    name: tlias-cms

  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: password

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml